CREATE TABLE USER (
id BIGINT AUTO_INCREMENT PRIMARY KEY
);


CREATE TABLE USER_DATA(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
user_id BIGINT,
FOREIGN KEY (user_id) REFERENCES USER(id)
);


CREATE TABLE GIFT_CARD(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
store_name VARCHAR(100) NOT NULL,
card_code VARCHAR(100) NOT NULL,
expiry_date DATE,
balance DOUBLE,
logo_image VARCHAR(100),
user_id BIGINT,
FOREIGN KEY (user_id) REFERENCES USER(id)
);




